### ISSUE TITLE
Please rename adapter to ioBroker.wrapper

### ISSUE THREAD

**Issue by GermanBluefox** [ausHaus/ioBroker.home#2]
Так как home это слишком абстрактно, не мог бы ты переименовать драйвер в wrapper?

Спасибо!

**Comment by Apollon77** [comment]
After rename (would be really great) I can support you to add basic adapter testing.

Google:translate: После переименования (было бы действительно здорово) я могу поддержать вас, чтобы добавить базовое тестирование адаптера.

Ingo

**Comment by ausHaus** [comment]
Ok
